### ISSUE TITLE
Potential incompatibility with some mods

### ISSUE THREAD

**Issue by 131iodine** [Provismet/Extra-Damage-Enchantments#2]
### Type of Error

Incorrect Behaviour

### Mod List

- Graveyard
- Realm RPG: Imps & Demons
- Realm RPG: Creep & Crop

### Description

**I am using Forge & Sinytra Connector but I tested on Fabric too and had the same issue**
I can't add mobs from these mods. I had no issues adding a neutral Snuffle mob (Snuffles mod) or Vanilla mobs.

Graveyard - Tested on Acolyte mob, cause he isn't Undead. The mob can't be added to a group, adding creeper to the same group works fine and extra damage and effect are applied to Creeper but not to Acolyte. Tested both on Fabric and Forge+Sinytra Connector.
Realm RPG: Imps & Demons - (No fabric version) Can't add any mob. They have a "demon" tag tho, which I tried to change to "outerworldly" for example but it didn't fix anything.
Realm RPG: Creep & Crop - (No fabric version) Same

I tried adding mobs to different groups with the same result.
Sorry if it's not a bug but me doing something wrong.

### Mod Version

1.2.0+1.20.1

### Minecraft Version

1.20.1 (both Fabric and Forge+Sinytra Connector)

### Mod Loader

Fabric, Other (specify in desc)

### Steps to Reproduce

- To avoid errors I didn't even make a datapack and edited tags straight in mod files. 
- Added mob tags to outerworldly.json for example to look like this:
```
{
  "replace": false,
  "values": [
        "minecraft:creeper",
	"graveyard:acolyte"
  ]
}
```
- Made a sword with Voidrender enchantment.
- Tested on creeper and acolyte

**Comment by Provismet** [comment]
Due to limitations in how modding itself works, only mobs that do not have a pre-existing group can be assigned a new one.

The Acolyte is hard-coded as an Illager (Rebel will work against it). Thus you can't change the group to something else.  
I assume the same to be true for Realm RPG mobs, but those are closed source so I can't offer any insight into it.

The easiest method to check if this works would be to also use [Provi's Health Bars](https://www.curseforge.com/minecraft/mc-mods/provihealth). It displays the "entity groups" on the HUD, including the custom ones from ExtraDE.

Any mob that does not have a hard-coded group can be moved into a new one.

Mojang is removing the group system in 1.20.5 anyway and replacing it with tags *very* similar to what ExtraDE is already doing, so if your other mods update then this problem will disappear.

**Comment by 131iodine** [comment]
Thank you for the explanation. It makes sense now.
One question. This icon means **unknow group** or **no group**, right?



![Image](https://github.com/Provismet/Extra-Damage-Enchantments/assets/73848389/161dd223-f0bd-40d5-865e-37d72b65962b)

**Comment by Provismet** [comment]
That is the default one, yes. Groups are not registered the same way items and mobs are, PHB cannot detect groups that aren't explicitly shown to it. ExtraDE uses an API to show all its new groups to PHB.

You can look at a Zombie for comparison.
